//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRP_1._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class Case
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Case()
        {
            this.TimeRegistrations = new HashSet<TimeRegistration>();
        }
    
        public int Case_No { get; set; }
        public string Title { get; set; }
        public string Case_Comment { get; set; }
        public Nullable<int> Type_Id { get; set; }
        public Nullable<int> Customer_Id { get; set; }
        public Nullable<System.DateTime> Date_Time_Created { get; set; }
        public Nullable<int> Created_By_User_Id { get; set; }
        public Nullable<System.DateTime> Last_Edit_Date_Time { get; set; }
        public Nullable<int> Last_Edit_By_User_Id { get; set; }
        public string Status { get; set; }
        public string Worked_Time_in_Minutes { get; set; }
        public string Manual_Work_Time { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual TypeofCas TypeofCas { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TimeRegistration> TimeRegistrations { get; set; }
    }
}
