//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRP_1._0 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceLangfr {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceLangfr() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TRP_1._0.ResourceLangfr", typeof(ResourceLangfr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to action Commentaire.
        /// </summary>
        internal static string actionComment {
            get {
                return ResourceManager.GetString("actionComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to actif.
        /// </summary>
        internal static string active {
            get {
                return ResourceManager.GetString("active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to actif Cas.
        /// </summary>
        internal static string activeCase {
            get {
                return ResourceManager.GetString("activeCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to actif utilisateur.
        /// </summary>
        internal static string activeUser {
            get {
                return ResourceManager.GetString("activeUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouter.
        /// </summary>
        internal static string add {
            get {
                return ResourceManager.GetString("add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouter cas Type.
        /// </summary>
        internal static string addCaseType {
            get {
                return ResourceManager.GetString("addCaseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouter client.
        /// </summary>
        internal static string addCustomer {
            get {
                return ResourceManager.GetString("addCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouter un nouvel utilisateur.
        /// </summary>
        internal static string addNewUser {
            get {
                return ResourceManager.GetString("addNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouter un utilisateur.
        /// </summary>
        internal static string addUser {
            get {
                return ResourceManager.GetString("addUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cas Commentaire.
        /// </summary>
        internal static string caseComment {
            get {
                return ResourceManager.GetString("caseComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cas n °.
        /// </summary>
        internal static string caseNo {
            get {
                return ResourceManager.GetString("caseNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cas.
        /// </summary>
        internal static string cases {
            get {
                return ResourceManager.GetString("cases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cas Statut.
        /// </summary>
        internal static string caseStatus {
            get {
                return ResourceManager.GetString("caseStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cas Titre.
        /// </summary>
        internal static string caseTitle {
            get {
                return ResourceManager.GetString("caseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cas Type.
        /// </summary>
        internal static string caseType {
            get {
                return ResourceManager.GetString("caseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fermé.
        /// </summary>
        internal static string closed {
            get {
                return ResourceManager.GetString("closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créer Cas.
        /// </summary>
        internal static string createCase {
            get {
                return ResourceManager.GetString("createCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créer Cas ligne.
        /// </summary>
        internal static string createCaseLine {
            get {
                return ResourceManager.GetString("createCaseLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client.
        /// </summary>
        internal static string customer {
            get {
                return ResourceManager.GetString("customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom du client.
        /// </summary>
        internal static string customerName {
            get {
                return ResourceManager.GetString("customerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client  n °.
        /// </summary>
        internal static string customerNo {
            get {
                return ResourceManager.GetString("customerNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La description.
        /// </summary>
        internal static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to modifier.
        /// </summary>
        internal static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifier le rapport d&apos;action.
        /// </summary>
        internal static string editActionReport {
            get {
                return ResourceManager.GetString("editActionReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifier la clientèle.
        /// </summary>
        internal static string editCustomer {
            get {
                return ResourceManager.GetString("editCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifier l&apos;utilisateur.
        /// </summary>
        internal static string editUser {
            get {
                return ResourceManager.GetString("editUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date de fin.
        /// </summary>
        internal static string endDate {
            get {
                return ResourceManager.GetString("endDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactif.
        /// </summary>
        internal static string inactive {
            get {
                return ResourceManager.GetString("inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facture d&apos;achat.
        /// </summary>
        internal static string invoice {
            get {
                return ResourceManager.GetString("invoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La langue.
        /// </summary>
        internal static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gérante.
        /// </summary>
        internal static string manager {
            get {
                return ResourceManager.GetString("manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to prénom.
        /// </summary>
        internal static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prochain.
        /// </summary>
        internal static string next {
            get {
                return ResourceManager.GetString("next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non.
        /// </summary>
        internal static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        internal static string number {
            get {
                return ResourceManager.GetString("number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ouvert.
        /// </summary>
        internal static string open {
            get {
                return ResourceManager.GetString("open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autre Sélection de cas.
        /// </summary>
        internal static string otherCaseSelection {
            get {
                return ResourceManager.GetString("otherCaseSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to précédent.
        /// </summary>
        internal static string previous {
            get {
                return ResourceManager.GetString("previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cas récents.
        /// </summary>
        internal static string recentCases {
            get {
                return ResourceManager.GetString("recentCases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sauvegarde.
        /// </summary>
        internal static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chercher.
        /// </summary>
        internal static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date de début.
        /// </summary>
        internal static string startDate {
            get {
                return ResourceManager.GetString("startDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date de début / Heure.
        /// </summary>
        internal static string startDateTime {
            get {
                return ResourceManager.GetString("startDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to statut.
        /// </summary>
        internal static string status {
            get {
                return ResourceManager.GetString("status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrêt Date / Heure.
        /// </summary>
        internal static string stopDateTime {
            get {
                return ResourceManager.GetString("stopDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temps en minutes.
        /// </summary>
        internal static string timeInMinutes {
            get {
                return ResourceManager.GetString("timeInMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HEURE PROGRAMME D&apos;INSCRIPTION.
        /// </summary>
        internal static string timeRegistrationProgramTitle {
            get {
                return ResourceManager.GetString("timeRegistrationProgramTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mettre à jour.
        /// </summary>
        internal static string update {
            get {
                return ResourceManager.GetString("update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilisateur.
        /// </summary>
        internal static string user {
            get {
                return ResourceManager.GetString("user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oui.
        /// </summary>
        internal static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
    }
}
